finalproject/moviewebsite/displayapp/urls.py
from django.urls import path
from . import views
app_name='displayapp'
urlpatterns = [
    path('',views.index,name='index'),
    path('about',views.about,name='about'),
    path('add',views.add_movie,name='add_movie'),
    path('movie/<int:movie_id>/',views.detail,name='detail'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/',views.delete,name='delete'),
]

finalproject/moviewebsite/movieapp/urls.py
from django.urls import path
from . import views
app_name='movieapp'
urlpatterns = [

    path('/register',views.register,name='register'),
    path('/login',views.login,name='login'),
    path('/logout', views.logout, name='logout'),
]

finalproject/moviewebsite/moviewebsite/urls.py
from moviewebsite import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movieapp',include('movieapp.urls')),
    path('',include('displayapp.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

finalproject/moviewebsite/displayapp/models.py
from django.db import models



class Movie(models.Model):
    name = models.CharField(max_length=250)
    desc = models.TextField()
    year = models.DateField()
    img = models.ImageField(upload_to='gallery/')
    director = models.CharField(max_length=250)
    producer = models.CharField(max_length=250)
    cast = models.TextField()

    def __str__(self):
        return self.name

finalproject/moviewebsite/movieapp/models.py
from django.db import models

# Create your models here.

finalproject/moviewebsite/displayapp/forms.py
from django import forms
from . models import Movie


class MovieForm(forms.ModelForm):
    class Meta:
        model=Movie
        fields=['name','desc','year','img','director','producer','cast']

finalproject/moviewebsite/displayapp/views.py
from django.shortcuts import render, redirect


from .forms import MovieForm
from .models import Movie


def index(request):
    movie = Movie.objects.all()
    return render(request,'index.html', {'movie':movie})
def add_movie(request):
    if request.method=="POST":
        name=request.POST.get('name')
        desc = request.POST.get('desc')
        year = request.POST.get('year')
        img = request.FILES['img']
        director = request.POST.get('director')
        producer = request.POST.get('producer')
        cast = request.POST.get('cast')
        movie=Movie(name=name,desc=desc,year=year,img=img,director=director,producer=producer,cast=cast)
        movie.save()
    return render(request,'add.html')
def about(request):
    return render(request,'about.html')
def detail(request,movie_id):
    movie=Movie.objects.get(id=movie_id)
    return render(request,"detail.html",{'movie':movie})
def update(request,id):
    movie=Movie.objects.get(id=id)
    form=MovieForm(request.POST or None, request.FILES,instance=movie)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'form':form,'movie':movie})

def delete(request,id):
    if request.method=='POST':
        movie=Movie.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render(request,'delete.html')

finalproject/moviewebsite/movieapp/views.py
from django.contrib import auth, messages
from django.contrib.auth.models import User
from django.shortcuts import render, redirect


# Create your views here.

def login(request):
    if request.method =='POST':
        name=request.POST['name']
        password=request.POST['password']
        user=auth.authenticate(username=name,password=password)

        if user is not None:
            auth.login(request,user)
            return redirect('/')
        else:
            messages.info(request,"Invalid Login")
            return redirect('login')

    return render(request,'login.html')

def register(request):
    if request.method=='POST':
        name=request.POST['username']
        email = request.POST['email']
        password = request.POST['password']
        cpassword = request.POST['password1']
        if password==cpassword:
            if User.objects.filter(username=name).exists():
                messages.info(request,"Username Taken")
                return redirect("register")
            if User.objects.filter(email=email).exists():
                messages.info(request,"email Taken")
                return redirect("register")
            else:
                user=User.objects.create_user(username=name,email=email,password=password)
                user.save();
                print("user created")
            return redirect('/')

        else:
            messages.info(request,"password not matching")
            return redirect('/register')
        return redirect('/')
    return render(request,"register.html")

def logout(request):
    auth.logout(request)
    return redirect('/')

finalproject/moviewebsite/templates/add.html
{% block body %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="text" name="name" placeholder="Name"><br>
    <input type="text" name="desc" placeholder="Description"><br>
    <input type="date" name="year" placeholder="Release date"><br>
    <input type="file" name="img"><br>
    <input type="text" name="director" placeholder="director"><br>
    <input type="text" name="producer" placeholder="producer"><br>
    <input type="text" name="cast" placeholder="cast"><br>

    <input type="submit">

</form>




{% endblock %}

finalproject/moviewebsite/templates/delete.html
<form method="post">
    {% csrf_token %}
    Are you want to delete this movie?
    <input type="submit">
</form>

finalproject/moviewebsite/templates/detail.html
{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{movie.img.url}}" width="300" height="300">
        </div>
    <div class="col-md-6">
        <h4>{{movie.name}}</h4>
        <h6>{{movie.desc}}</h6>
        <h6>{{movie.year}}</h6>
        <a class="btn btn-warning" href="{% url 'displayapp:update' movie.id%}">Update</a>
        <a class="btn btn-danger" href="{% url 'displayapp:delete' movie.id%}">Delete</a>
    </div>

 </div>
</div>

{% endblock %}

finalproject/moviewebsite/templates/edit.html
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit">
</form>

finalproject/moviewebsite/templates/index.html
{% load static %}}
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>Movie Hunter</title>
<!--

Template 2101 Insertion

http://www.tooplate.com/view/2101-insertion

-->
  <!-- load CSS -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400">        <!-- Google web font "Open Sans" -->
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">                                            <!-- https://getbootstrap.com/ -->
  <link rel="stylesheet" href="{% static 'css/fontawesome-all.min.css' %}">                                      <!-- Font awesome -->
  <link rel="stylesheet" href="{% static 'css/tooplate-style.css' %}">                                           <!-- Templatemo style -->

  <script>
    var renderPage = true;

    if (navigator.userAgent.indexOf('MSIE') !== -1
      || navigator.appVersion.indexOf('Trident/') > 0) {
      /* Microsoft Internet Explorer detected in. */
      alert("Please view this in a modern browser such as Chrome or Microsoft Edge.");
      renderPage = false;
    }
  </script>

</head>

<body>

  <!-- Loader -->
  <div id="loader-wrapper">
    <div id="loader"></div>
    <div class="loader-section section-left"></div>
    <div class="loader-section section-right"></div>
  </div>

  <div class="tm-main">

    <div class="tm-welcome-section">
      <div class="container tm-navbar-container">
        <div class="row">
          <div class="col-xl-12">
            <nav class="navbar navbar-expand-sm">
              <ul class="navbar-nav ml-auto">
                <li class="nav-item active">
                  <a href="index.html" class="nav-link tm-nav-link tm-text-white active">Home</a>
                </li>
                <li class="nav-item">
                  <a href="about" class="nav-link tm-nav-link tm-text-white">About</a>
                </li>
                <li class="nav-item">
                  <a href="add" class="nav-link tm-nav-link tm-text-white">Add Movie</a>
                </li>
                  {% if user.is_authenticated %}
                <li class="nav-link tm-nav-link tm-text-white">Hello {{user.username}}</li>
                <li><a href="movieapp/logout" class="nav-link tm-nav-link tm-text-white">Logout</a></li>

                {% else %}
                <li><a href="movieapp/register" class="nav-link tm-nav-link tm-text-white">Register</a></li>
                <li><a href="movieapp/login" class="nav-link tm-nav-link tm-text-white">Login</a></li>
                {% endif %}
              </ul>
            </nav>
          </div>
        </div>
      </div>

      <div class="container text-center tm-welcome-container">
        <div class="tm-welcome">
          <i class="fas tm-fa-big fa-music tm-fa-mb-big"></i>
          <h1 class="text-uppercase mb-3 tm-site-name">Movie Hunter</h1>
          <p class="tm-site-description">Movie Lovers</p>
        </div>
      </div>

    </div>

    <div class="container">
      <div class="tm-search-form-container">
        <form action="index.html" method="GET" class="form-inline tm-search-form">
          <div class="text-uppercase tm-new-release">New Release</div>
          <div class="form-group tm-search-box">
            <input type="text" name="keyword" class="form-control tm-search-input" placeholder="Type your keyword ...">
            <input type="submit" value="Search" class="form-control tm-search-submit">
          </div>
          <div class="form-group tm-advanced-box">
            <a href="https://www.google.com/" class="tm-text-white">Go Advanced ...</a>
          </div>
        </form>
      </div>

      <div class="row tm-albums-container grid">
        {% for i in movie %}
        <div class="col-sm-6 col-12 col-md-6 col-lg-3 col-xl-3 tm-album-col">
          <figure class="effect-sadie">
            <div class="col">
                <a href="{% url 'displayapp:detail' i.id %}" class="btn btn-primary">More Details</a><br><br>
              </div>
            <img src="{{i.img.url}}" alt="Image" class="img-fluid">
            <figcaption>
              <h2>New Release</h2>
              <p>{{i.year}}</p>
<!--               <p>{{i.director}}</p>-->
<!--               <p>{{i.producer}}</p>-->
<!--               <p>{{i.cast}}</p>-->

            </figcaption>

          </figure>

        </div>

        {% endfor %}

      </div>






      <div class="row mb-5">
        <div class="col-xl-12">
          <div class="media-boxes">
            <div class="media">
              <img src="{% static 'img/bahubali.jpg' %}" width="150px" height="150px" alt="Image" class="mr-3">
              <div class="media-body tm-bg-gray">
                <div class="tm-description-box">
                  <h5 class="tm-text-blue">Bahubali</h5>
                  <p class="mb-0">The Goat Life is an upcoming survival drama film written,and directed by Blessy.  It is an adaptation of the 2008 Malayalam novel by Benyamin, which is based on a true incident. <a href="https://google.com/search?q=aadujeevitham" target="_parent">aadujeevitham</a>. Thank you.</p>
                </div>
                <div class="tm-buy-box">
                  <a href="#" class="tm-bg-blue tm-text-white tm-buy">buy</a>
                  <span class="tm-text-blue tm-price-tag">$50.0</span>
                </div>
              </div>
            </div>

            <div class="media">
              <img src="{% static 'img/minnalmurali.jpg' %}" width="150px" height="150px" alt="Image" class="mr-3">
              <div class="media-body tm-bg-pink-light">
                <div class="tm-description-box">
                  <h5 class="tm-text-pink">Minnalmurali</h5>
                  <p class="mb-0">The franchise consists mainly of three CGI-animated films: Kung Fu Panda (2008), Kung Fu Panda 2 (2011), and Kung Fu Panda 3 (2016) with a fourth film scheduled for release in 2024</p>
                </div>
                <div class="tm-buy-box">
                  <a href="#" class="tm-bg-pink tm-text-white tm-buy">buy</a>
                  <span class="tm-text-pink tm-price-tag">$70.0</span>
                </div>
              </div>
            </div>

            <div class="media">
              <img src="{% static 'img/spiderman.jfif' %}" height="150px" width="150px" alt="Image" class="mr-3">
              <div class="media-body tm-bg-gray">
                <div class="tm-description-box">
                  <h5 class="tm-text-blue">Spiderman</h5>
                  <p class="mb-0">Spider-Man is a superhero appearing in American comic books published by Marvel Comics. Created by writer-editor Stan Lee and artist Steve Ditko, </p>
                </div>
                <div class="tm-buy-box">
                  <a href="#" class="tm-bg-blue tm-text-white tm-buy">buy</a>
                  <span class="tm-text-blue tm-price-tag">$50.0</span>
                </div>
              </div>
            </div>

            <div class="media">
              <img src="{% static 'img/shershaah.jpg' %}" height="150px" width="150px" alt="Image" class="mr-3">
              <div class="media-body tm-bg-pink-light">
                <div class="tm-description-box">
                  <h5 class="tm-text-pink">Shershaah</h5>
                  <p class="mb-0">Curabitur id tempor orci. Fusce efficitur in enim sit amet sodales. Proin id gravida leo. Phasellus non quam et justo faucibus rhoncus.</p>
                </div>
                <div class="tm-buy-box">
                  <a href="#" class="tm-bg-pink tm-text-white tm-buy">buy</a>
                  <span class="tm-text-pink tm-price-tag">$30.0</span>
                </div>
              </div>
            </div>

            <div class="media">
              <img src="{% static 'img/titanic.jpg' %}" height="150px" width="150px" alt="Image" class="mr-3">
              <div class="media-body tm-bg-gray">
                <div class="tm-description-box">
                  <h5 class="tm-text-blue">Titanic</h5>
                  <p class="mb-0">Maecenas sit amet nibh faucibus, tincidunt nisl sit amet, elementum eros. Fusce congue ligula gravida lorem lacinia.</p>
                </div>
                <div class="tm-buy-box">
                  <a href="#" class="tm-bg-blue tm-text-white tm-buy">buy</a>
                  <span class="tm-text-blue tm-price-tag">$50.0</span>
                </div>
              </div>
            </div>
          </div> <!-- media-boxes -->
        </div>
      </div>

      <div class="row tm-mb-big tm-subscribe-row">
        <div class="col-xl-6 col-lg-6 col-md-12 col-sm-12 tm-bg-gray tm-subscribe-form">
          <h3 class="tm-text-pink tm-mb-30">Subscribe our updates!</h3>
          <p class="tm-mb-30">Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Morbi semper, ligula et pretium porttitor, leo orci accumsan ligula.</p>
          <form action="index.html" method="POST">
            <div class="form-group mb-0">
              <input type="text" class="form-control tm-subscribe-input" placeholder="Your Email">
              <input type="submit" value="Submit" class="tm-bg-pink tm-text-white d-block ml-auto tm-subscribe-btn">
            </div>
          </form>
        </div>
        <div class="col-xl-6 col-lg-6 col-md-12 col-sm-12 img-fluid pl-0 tm-subscribe-img"></div>
      </div>

      <div class="row tm-mb-medium">
        <div class="col-xl-4 col-lg-4 col-md-4 col-sm-6 mb-4">
          <h4 class="mb-4 tm-font-300">Latest Albums</h4>
          <a href="#" class="tm-text-blue-dark d-block mb-2">Sed fringilla consectetur</a>
          <a href="#" class="tm-text-blue-dark d-block mb-2">Mauris porta nisl quis</a>
          <a href="#" class="tm-text-blue-dark d-block mb-2">Quisque maximus quam nec</a>
          <a href="#" class="tm-text-blue-dark d-block">Class aptent taciti sociosqu ad</a>
        </div>
        <div class="col-xl-4 col-lg-4 col-md-4 col-sm-6 mb-4">
          <h4 class="mb-4 tm-font-300">Our Pages</h4>
          <a href="#" class="tm-text-blue-dark d-block mb-2">Nam dapibus imperdiet</a>
          <a href="#" class="tm-text-blue-dark d-block mb-2">Primis in faucibus orci</a>
          <a href="#" class="tm-text-blue-dark d-block mb-2">Sed interdum blandit dictum</a>
          <a href="#" class="tm-text-blue-dark d-block">Donec non blandit nisl</a>
        </div>
        <div class="col-xl-4 col-lg-4 col-md-4 col-sm-6">
          <h4 class="mb-4 tm-font-300">Quick Links</h4>
          <a href="#" class="tm-text-blue-dark d-block mb-2">Nullam scelerisque mauris</a>
          <a href="#" class="tm-text-blue-dark d-block mb-2">Vivamus tristique enim non orci</a>
          <a href="#" class="tm-text-blue-dark d-block mb-2">Luctus et ultrices posuere</a>
          <a href="#" class="tm-text-blue-dark d-block">Cubilia Curae</a>
        </div>
      </div>
      <footer class="row">
        <div class="col-xl-12">
          <p class="text-center p-4">Copyright &copy; <span class="tm-current-year">2018</span> Your Company Name 
          
          - Design:  Tooplate</p>
        </div>
      </footer>
    </div> <!-- .container -->

  </div> <!-- .main -->

  <!-- load JS -->
  <script src="{% static 'js/jquery-3.2.1.slim.min.js' %}"></script> <!-- https://jquery.com/ -->
  <script>

    /* DOM is ready
    ------------------------------------------------*/
    $(function () {

      if (renderPage) {
        $('body').addClass('loaded');
      }

      $('.tm-current-year').text(new Date().getFullYear());  // Update year in copyright
    });

  </script>
<!--{% block body %}-->
<!--  <div clss="container">-->
<!--    <div class="row">-->
<!--        {% for i in res %}-->
<!--        <div class="col-md-3">-->
<!--            <div class="card" style="width: 18rem;">-->
<!--  <img class="card-img-top" src="{{i.img.url}}" alt="Card image cap" width="100px" height="200px">-->
<!--  <div class="card-body">-->
<!--    <h5 class="card-title">{{i.name}}</h5>-->
<!--     <h4 class="card-title">{{i.details}}</h4>-->
<!--&lt;!&ndash;    <p class="card-text">{{i.desc}}</p>&ndash;&gt;-->
<!--    <a href="{% url 'displayapp:detail' i.id %}" class="btn btn-primary">More Details</a><br><br>-->
<!--  </div>-->
<!--</div>-->
<!--        </div>-->
<!--        {% endfor %}-->
<!--    </div>-->
<!--</div>-->

<!--{% endblock %}-->
</body>
</html>

finalproject/moviewebsite/templates/login.html
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>login</title>
    <style>
        form{text-align:center;
        margin-top:50px;
        margin-bottom:25px;
        margin-left:250px;
        margin-right:250px;
        margin-style:solid;


        padding:12px 20px;
          border: 2px solid #ccc;
           border-radius: 4px;

        }
        body{
       background-image: url({% static 'images\1page-img4.jpg' %});
       background-repeat:no-repeat;
       top: 0;
	   left: 0;
	   width: 100%;
	   height: 100%;
	   background-repeat: no-repeat;
	   background-size: cover;
	   background-position: center;
       }

  input[type=button], input[type=submit], input[type=reset] {
  background-color: #04AA6D;
  border: none;
  color: white;
  padding: 16px 32px;
  text-decoration: none;
  margin: 4px 2px;
  cursor: pointer;
  }
  input[type=text],input[type=password] {
  width:99%;
  padding: 12px;
  border: 1px solid #ccc;
  border-radius: 4px;
  resize: vertical;
}

label {
   color:black;
  padding: 12px 12px 12px 0;
  display: inline-block;
  float:left;
}
    </style>
</head>
<body>
<h2>Please Login</h2>
<form action="login" method="post">
    {% csrf_token %}
    <label>Name:</label>
    <input type="text" name="name" placeholder="username"></br></br>
    <label>Password:</label>
    <input type="password" name="password" placeholder="password"></br></br>
    <input type="submit" name="Login">
</form>
</body>
</html>

finalproject/moviewebsite/templates/register.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>registration</title>
    <style>
        form{text-align:center;
        margin-top:50px;
        margin-bottom:25px;
        margin-left:250px;
        margin-right:250px;
        margin-style:solid;

        padding:12px 20px;
          border: 2px solid #ccc;
           border-radius: 4px;

        }
        input[type=button], input[type=submit], input[type=reset] {
  background-color: #04AA6D;
  border: none;
  color: white;
  padding: 16px 32px;
  text-decoration: none;
  margin: 4px 2px;
  cursor: pointer;
  }
  body{
  background-image:url({% static 'images\1page-img3.jpg' %});
    top: 0;
	left: 0;
	width: 100%;
	height: 100%;
	background-repeat: no-repeat;
	background-size: cover;
	background-position: center;
  }
  input[type=text],input[type=email],input[type=password] {
  width:100%;
  padding: 12px;
  border: 1px solid #ccc;
  border-radius: 4px;
  resize: vertical;
  position:center;
}

label {

  padding: 12px 12px 12px 0;
  display: inline-block;
  float:left;
}
h1{text-align:center;
color:white;
}

h2
{
color:orange;
text-align:center;
}
    </style>
</head>
<body>
<h1>Register Here</h1><br><br>
<form action="register" method="post">
    {% csrf_token %}
    <label>Name:</label>
    <input type="text" name="username" placeholder="username"><br><br><br><br>
<label>Email ID:</label>
<input type="email" name="email" placeholder="email"><br><br>
<label>Password:</label>
<input type="password" name="password" placeholder="password"><br><br>
<label>Confirm Password:</label>
<input type="password" name="password1" placeholder="confirm password"><br><br>
    <input type="submit" name="submit"><br><br>
    </form>

</body>
</html>